#
# * CMSC 216 (Fall 2020)
# * Section: 0303 (M/W 8am)
# * University ID: 117568813
# * Directory ID: amattu
# *
# * Author: Alec M.
# * Date: Oct 28th, 2020
# *
# * I pledge on my honor that I have not given or received
# * any unauthorized assistance on this assignment.
#

#
# Define make variables
#
GC = gcc
FLAGS = -ansi -pedantic-errors -Wall -Werror -Wshadow -fstack-protector-all

#
# Define main target options
#

#
# Define target operations
#

#
# Define object operations
#

#
# Define a "clean" option
#
clean:
	rm -f *.x *.o
