#
# * CMSC 216 (Fall 2020)
# * Section: 0303 (M/W 8am)
# * University ID: 117568813
# * Directory ID: amattu
# *
# * Author: Alec M.
# * Date:
# *
# * I pledge on my honor that I have not given or received
# * any unauthorized assistance on this assignment.
#

#
# Define make variables
#
GC = gcc
FLAGS = -ansi -pedantic-errors -Wall -Werror -Wshadow -fstack-protector-all

#
# Define main target options
#
all: public01.x public02.x public03.x public04.x public05.x public06.x \
	public07.x public08.x public09.x public10.x

#
# Define target operations
#

#
# Define object operations
#


#
# Define a "clean" option
#
clean:
	rm -f *.x public**.o
