#
# Define make variables
#
GC = gcc
FLAGS = -ansi -pedantic-errors -Wall -Werror -Wshadow -fstack-protector-all

#
# Define an "all" option
#
all: program1.x main.x tester.x

#
# Define a "clean" option
#
clean: rm -f *.x *.o
