#!/bin/tcsh

#
# This test checks the exit status of your program on an input that has
# fewer than 200 words.  The ">& /dev/null" just throws away all of your
# program's output, because we don't care about it for this test- only its
# exit status is being examined.
#

# (c) Larry Herman, 2020.  You are allowed to use this code yourself, but
# not to provide it to anyone else.

./paper-length.x < document1 >& /dev/null

if ($status == 1) then
  echo 'Success!'
  exit 0
else
  echo
  echo 'Failure!  (Exit status differed from expected output.)'
  exit -1
endif
