#!/bin/tcsh

#
# This test checks the output of your program on an input that has more than
# 200 words.
#

# (c) Larry Herman, 2020.  You are allowed to use this code yourself, but
# not to provide it to anyone else.

# due to the behavior of tcsh (not explained in detail here) this setting is
# needed to be able to properly detect whether the diff command below
# succeeded
unset anyerror

./paper-length.x < document2 | diff -wi - public2.results

if (!($status)) then
  echo 'Success!'
  exit 0
else
  echo
  echo 'Failure!  (Output differed from expected output.)'
  exit -1
endif
