#!/bin/tcsh -f

# CMSC 216, Fall 2020, Project #12
# Public test 8 (public08)
#
# Tests running the third program to compute sopd(2, 1).
#
# (c) Larry Herman, 2020.  You are allowed to use this code yourself, but
# not to provide it to anyone else.

spim -file prog3.s < public08.inputdata | tail -n +2
