#!/bin/tcsh -f

# CMSC 216, Fall 2020, Project #12
# Public test 9 (public09)
#
# Tests running the third program to compute sopd(2, 16).
#
# (c) Larry Herman, 2020.  You are allowed to use this code yourself, but
# not to provide it to anyone else.

spim -file prog3.s < public09.inputdata | tail -n +2
