#!/bin/tcsh -f

# CMSC 216, Fall 2020, Project #12
# Public test 3 (public03)
#
# Tests running the first program to compute 6^3.
#
# (c) Larry Herman, 2020.  You are allowed to use this code yourself, but
# not to provide it to anyone else.

spim -file prog1.s < public03.inputdata | tail -n +2
