#!/bin/tcsh -f

# CMSC 216, Fall 2020, Project #12
# Secret test 4 (secret04)
#
# Tests running the first program to compute 7^-5, which mathematically
# would be a (non-integer) real number, but prog1.c prints 1 for it, so your
# first assembly program should do the same.
#
# (c) Larry Herman, 2020.  You are allowed to use this code
# yourself, but not to provide it to anyone else.

spim -file prog1.s < secret04.inputdata | tail -n +2
