#!/bin/tcsh -f

# CMSC 216, Fall 2020, Project #12
# Secret test 1 (secret01)
#
# Tests running the first program to compute 216^0.
#
# (c) Larry Herman, 2020.  You are allowed to use this code
# yourself, but not to provide it to anyone else.

spim -file prog1.s < secret01.inputdata | tail -n +2
