#!/bin/tcsh -f

# CMSC 216, Fall 2020, Project #12
# Secret test 15 (secret15)
#
# Tests running the third program to compute sopd(1, 1).
#
# (c) Larry Herman, 2020.  You are allowed to use this code
# yourself, but not to provide it to anyone else.

spim -file prog3.s < secret15.inputdata | tail -n +2
