#!/bin/tcsh -f

# CMSC 216, Fall 2020, Project #12
# Secret test 9 (secret09)
#
# Tests running the second program to compute sopd(123, -2).
#
# (c) Larry Herman, 2020.  You are allowed to use this code
# yourself, but not to provide it to anyone else.

spim -file prog2.s < secret09.inputdata | tail -n +2
