#!/bin/tcsh -f

# CMSC 216, Fall 2020, Project #12
# Secret test 2 (secret02)
#
# Tests running the first program to compute 0^0.
#
# (c) Larry Herman, 2020.  You are allowed to use this code
# yourself, but not to provide it to anyone else.

spim -file prog1.s < secret02.inputdata | tail -n +2
