#!/bin/tcsh -f

# CMSC 216, Fall 2020, Project #12
# Secret test 18 (secret18)
#
# Tests running the third program to compute sopd(-4, -5).
#
# (c) Larry Herman, 2020.  You are allowed to use this code
# yourself, but not to provide it to anyone else.

spim -file prog3.s < secret18.inputdata | tail -n +2
