#!/bin/tcsh -f

# CMSC 216, Fall 2020, Project #12
# Secret test 5 (secret05)
#
# Tests running the second program to compute sopd(0, 0).
#
# (c) Larry Herman, 2020.  You are allowed to use this code
# yourself, but not to provide it to anyone else.

spim -file prog2.s < secret05.inputdata | tail -n +2
