#!/bin/tcsh -f

# CMSC 216, Fall 2020, Project #12
# Secret test 17 (secret17)
#
# Tests running the third program to compute sopd(-3, 234).
#
# (c) Larry Herman, 2020.  You are allowed to use this code
# yourself, but not to provide it to anyone else.

spim -file prog3.s < secret17.inputdata | tail -n +2
